### ISSUE TITLE
Failing to nuke server

### ISSUE THREAD

**Issue by TheHectoret** [Bad-Discord/Discord-Nuker#4]
```
Traceback (most recent call last):
  File "C:\Users\Ettore Morini\Documents\Discord-Nuker-main\main.py", line 994, in <module>
    start(args)
  File "C:\Users\Ettore Morini\Documents\Discord-Nuker-main\main.py", line 989, in start
    asyncio.run(main(token, guild))
  File "C:\Users\Ettore Morini\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Ettore Morini\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Ettore Morini\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
  File "C:\Users\Ettore Morini\Documents\Discord-Nuker-main\main.py", line 721, in main
    names = [i % name for i in names]
TypeError: not all arguments converted during string formatting  

```

I get this error when it asks for my name when I want to nuke a server. Am I doing something wrong or is it the code? I'm on Windows 11 with Python 3.13.1.

**Comment by M-logique** [comment]
I'm going to archive this repo because I won't be making any commits in the next 6 months.
